# Generated by Django 3.2.7 on 2021-09-28 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
                ('adscripcion', models.CharField(max_length=150)),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOCTURNO', 'Nocturno'), ('MOVIL', 'Movil')], max_length=15)),
                ('sexo', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=10)),
                ('antiguedad', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 9, 28, 12, 14, 43, 715944))),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
    ]
